services:
  server:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
    ports:
      - "4173:4173"
    env_file:
      - ./client/.env
    depends_on:
      - server

